version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    container_name: kibana
    links:
      - logstash:logstash
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
    container_name: logstash
    ports:
      - 5000:5000/udp
    volumes:
      - ./settings/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

volumes:
  esdata:
    driver: local
