filebeat.prospectors:
- input_type: log
  paths:
    - /mnt/log/json.log
  json.message_key: event
  json.keys_under_root: true
  fields:
    type: is_json
  tags: [
    "json-log"
  ]

- input_type: log
  paths:
    - /mnt/log/multiline.log
  fields:
    type: is_multiline
  tags: [
    "multiline-log"
  ]
  multiline.pattern: '^[[:space:]-\[]'
  multiline.negate: false
  multiline.match: after

- input_type: log
  paths:
    - /mnt/log/text.log
  fields:
    type: is_text
  tags: [
    "text-log"
  ]

output.logstash:
  hosts: ["logstash:5044"]
